### PR TITLE
Add featured photos screensaver from google

### PR DESCRIPTION
**Pull request by huphtur**
This should handle #18 

Note: image was compressed with ImageOptim.

### CODE REVIEW

**Comment by agarrharr** [comment]
Thanks! I guess I was too lazy to do this before. Thanks for helping out!

I just realized that there might be a copyright issue here. This photo is at http://www.melfoody.com/p426720632/e61f66a34 and it's copyrighted. I am contacting the copyright holder for permission.

**Comment by huphtur** [comment]
Want me to grab another photo instead?

**Comment by agarrharr** [comment]
I believe we would have the same issue with any photo, unless you could find one in the public domain. Perhaps we could create a fake screenshot using a public domain photo...

But I'm no copyright expert and maybe using this photo is fine.

**Comment by agarrharr** [comment]
Let's do it.

**Pull request merged**
