### PR TITLE
Add Last Statement Screensaver

### PR DESCRIPTION
**Pull request by amiantos**
- adds my new FOSS screensaver, Last Statement

### CODE REVIEW

**Comment by agarrharr** [comment]
I can't seem to get it installed. It looks like it installed, but it's not showing up in my list of screen savers...

**Comment by amiantos** [comment]
That's weird, I haven't had any similar problems on a couple computers I've installed it on. You do need to be on Mojave at least. Not sure what the problem could be.

**Comment by agarrharr** [comment]
I’m on Catalina. I can try again later and see if it works.

**Comment by agarrharr** [comment]
It installed for me now!

**Pull request merged**
