### PR TITLE
Add ColorClock screensaver

### PR DESCRIPTION
**Pull request by edwardloveall**
Hello! 😄 Thanks for your great list of screensavers. I've added mine here. Please let me know if there's anything I missed or you'd like me to change!

### CODE REVIEW

**Comment by agarrharr** [comment]
Thanks for submitting. Unfortunately, I can't get it to work on my computer. I got this message:

screen shot 2018-08-10 at 8 38 49 am

**Comment by edwardloveall** [comment]
Well, dang it. What version of macOS are you running? Also would you be willing to try selecting ColorClockSaver, quitting System Preferences with it still selected, then opening System Preferences again? This might be a [known bug](https://github.com/JohnCoates/Aerial/issues/4) with the macOS and swift.

**Comment by agarrharr** [comment]
I'm on macOS High Sierra 10.13.6. The screensaver actually worked, it just didn't show the preview. And then the next time I looked in System Preferences, the preview did work...

**Comment by edwardloveall** [comment]
Thank! 😄  Yeah it's an annoying Cocoa bug. Thanks for poking further and for the great list of screensavers!

**Pull request merged**
