### PR TITLE
Add Flip Clock Screensaver 

### PR DESCRIPTION
**Pull request by frykauf**
Why add it? - It can automatically dimm the screen.

Link again: https://www.smart-app.dev/downloads/downloads.html#

### CODE REVIEW

**Comment by agarrharr** [comment]
Sorry, I'm going to remove this screensaver from the list because I'm experiencing a bug.

Screen Shot 2021-09-16 at 08 26 04

**Comment by frykauf** [comment]
Hmm, are you on the latest version of the wallpaper? I use to sometimes experience that bug, but since the update I’ve yet to see it — maybe it got fixed.

Flip-settings
In preferences go to the Flip wallpaper and then click „Screen Saver Options…". Then click the update button to check if you really have the latest version.
That’s the most reliable way to check for update since I think the dev sometimes gives the Flip screensaver same version numbers.

**Comment by frykauf** [comment]
Also the bug might have disappeared because I chose „Install for all users“.

**Comment by frykauf** [comment]
> Yeah, it says I have the latest version... 😢
Yeah, I started having these issues since then as well, it might have been the update to macOS 11.6 or some other background OS update. I guess I’ll reply to this when the issues are fixed with an update so it can go back on the list.

**Comment by MadMacMad** [comment]
hello,
i'm the dev of the screensaver... 
have updated it and all bug's fixed... 
many thx
M.

**Comment by agarrharr** [comment]
Thanks. I added it back to the list.

**Pull request merged**
