### PR TITLE
Add (another) word clock

### PR DESCRIPTION
**Pull request by chrstphrknwtn**

### CODE REVIEW

**Comment by agarrharr** [comment]
This is fantastic! How did you make the gif?

**Comment by chrstphrknwtn** [comment]
Awesome!

To make the gif:  
QuickTime > New Screen Recording > After Effects > [Gifski](https://sindresorhus.com/gifski)

Because the screensaver is a WebView it was easy to load it in the browser and then record with QuickTime. Recorded the time changing, and then edited it together into a short MP4.

**Comment by agarrharr** [comment]
Oh ok. Thanks. I was wondering if I could make gifs for other screensavers, but probably not.

**Comment by chrstphrknwtn** [comment]
I figured out a generic way.

Create an AppleScript file:
````applescript
-- Up to Sierra
-- set screenSaverStart to "/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine"

-- High Sierra
set screenSaverStart to "/System/Library/CoreServices/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine"

tell application "QuickTime Player"
	set newScreenRecording to new screen recording
	tell newScreenRecording
		start
	end tell
	delay 2
	do shell script screenSaverStart
	tell newScreenRecording
		stop
	end tell
end tell
````

You can just copy paste this into the AppleScript Editor and play it, or put in a file:
````shell
osascript mysript.scpt
````

This will start a new screen recording, wait two seconds and launch the screen saver, then when screen saver exits, the screen recoding will then stop and you'll br presented with QuickTime movie of however long you let the screen saver run. BAM.

Then you can trim the movie in Quicktime before saving, and thenrun it through [Gifski](https://sindresorhus.com/gifski).

The resulting gifs can be pretty massive... but Gifski has settings for scaling, framerate, and quality. I've found that images / gif 888px result in no scaling in a GitHub readme.

**Comment by agarrharr** [comment]
That works great! Can you make a pull request to add this script to `contributing.md`? Or can you edit your comment to add an open source license? I would recommend [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/), since that's what this repository uses.

**Comment by chrstphrknwtn** [comment]
I just ran through the whole thing, seems to work ok... I reduced the width to 768px (minimum in Gifski).

File size might be an issue. For the monochrome compresses well... the flurry screensaver not so much.

untitled
4 seconds, 598kb


untitled2
5 seconds, **2.9mb**

**Comment by chrstphrknwtn** [comment]
Alternatively, converting and downscaling with `ffmpeg` creates very small files.

I just tried to embed `mp4s` into a GitHub readme, but video in readme.md is not supported: https://github.com/chrstphrknwtn/mp4-readme

However, there's an opportunity to make quite a nice GitHub pages branch for the repo:
https://chrstphrknwtn.github.io/mp4-readme/

Would you be up for a creating a nicely designed GitHub page with `mp4` previews for the repo? Something along the lines of http://padbury.me/clock/ ?

**Comment by agarrharr** [comment]
That would be awesome!

**Pull request merged**
